#在同一目录下,properties配置优先级> YAML配置优先级
# 在yaml设置的profile，properties文件也可以读到
spring:
    profiles:
      active: dev


server:
  error:
    include-exception: true

# yaml在配置文件中添加三个英文状态的短横线即可区分不同的profile
---
spring:
    profiles: dev
server:
  port: 8080
---
spring:
    profiles: test
server:
  port: 8081
learnboot:
    name: www.learnboot-test.com

---
spring:
    profiles: prod
server:
  port: 8082
learnboot:
    desc: ${learnboot.name} is a domain-prod name